#!/usr/bin/env python3
"""Reconstruct the sentence-wise GSAP-ERE LLM prompting pipeline."""

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
import os
import platform
import re
import socket
import subprocess
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


DEFAULT_DOCUMENT_ID = "00016_2106_09462.txt"
DEFAULT_RETRIEVER = "sentence-transformers/multi-qa-mpnet-base-cos-v1"

ENTITY_DEFINITIONS = (
    ("MLModel", "an explicitly named executable machine-learning model or model resource"),
    ("MLModelGeneric", "an unnamed or informal mention of one or more machine-learning models"),
    ("ModelArchitecture", "a named architecture, conceptual model type, backbone, or architectural component"),
    ("Method", "a method, technique, algorithmic procedure, representation, learning paradigm, loss, or optimizer"),
    ("Dataset", "an explicitly named dataset or dataset acronym"),
    ("DatasetGeneric", "an unnamed dataset mention, including spans expressing dataset size or instance type"),
    ("DataSource", "a named non-static source from which data are obtained, such as a website or social platform"),
    ("ReferenceLink", "an in-text citation marker linked to a bibliography entry"),
    ("Task", "a specific machine-learning task or a named collection of related tasks"),
    ("URL", "a literal URL in the sentence"),
)
ENTITY_TYPES = tuple(label for label, _ in ENTITY_DEFINITIONS)
ENTITY_ORDER = {label: index for index, label in enumerate(ENTITY_TYPES)}

RELATION_DEFINITIONS = (
    ("appliedTo", "subject model, method, or architecture is applied to object task"),
    ("architecture", "subject model/architecture has object architecture as its structure or component"),
    ("benchmarkFor", "subject dataset is a benchmark for object task"),
    ("citation", "subject scholarly entity is identified or supported by object ReferenceLink"),
    ("coreference", "subject and object denote exactly the same compatible entity; symmetric"),
    ("evaluatedOn", "subject model or method was evaluated or tested on object dataset"),
    ("generatedBy", "subject dataset was generated by object method or model"),
    ("hasInstanceType", "object span states the item or instance type of subject dataset"),
    ("isBasedOn", "subject model is derived from or based on object model"),
    ("isComparedTo", "subject and object are explicitly compared; symmetric"),
    ("isHyponymOf", "subject is a narrower instance or subclass of compatible object"),
    ("isPartOf", "subject is a part, split, member, or component of compatible object"),
    ("size", "object span states the size or volume of subject dataset"),
    ("sourcedFrom", "subject dataset originates from object DataSource"),
    ("trainedOn", "subject model or method was trained on object dataset"),
    ("transformedFrom", "subject dataset was transformed or derived from object dataset"),
    ("usedFor", "subject method supplies functionality used to create object model, method, or architecture"),
    ("url", "object URL gives the external location of subject scholarly entity"),
)
RELATION_TYPES = tuple(label for label, _ in RELATION_DEFINITIONS)
RELATION_ORDER = {label: index for index, label in enumerate(RELATION_TYPES)}
SYMMETRIC_RELATIONS = frozenset({"coreference", "isComparedTo"})
NER_OUTPUT_FORMATS = ("indices", "inline")
INLINE_MARKER_RE = re.compile(
    r"\[\[(?:(?P<close>/)(?P<close_id>e[1-9][0-9]*)|"
    r"(?P<open_id>e[1-9][0-9]*):(?P<label>[A-Za-z][A-Za-z0-9]*))\]\]"
)

CLOSE_PUNCTUATION = {",", ".", ";", ":", "!", "?", "%", ")", "]", "}", "'s"}
OPEN_PUNCTUATION = {"(", "[", "{"}
JOIN_BOTH_SIDES = {"-", "/", ":/"}


@dataclass(frozen=True)
class Entity:
    start: int
    end: int
    type: str


@dataclass(frozen=True)
class Relation:
    subject_start: int
    subject_end: int
    object_start: int
    object_end: int
    label: str


@dataclass(frozen=True)
class SentenceRecord:
    doc_id: str
    sentence_id: int
    tokens: tuple[str, ...]
    text: str
    entities: tuple[Entity, ...]
    relations: tuple[Relation, ...]

    @property
    def labels(self) -> frozenset[str]:
        return frozenset(entity.type for entity in self.entities)

    @property
    def key(self) -> str:
        return f"{self.doc_id}:{self.sentence_id}"


@dataclass(frozen=True)
class PairExample:
    record_index: int
    subject: Entity
    object: Entity
    label: str


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def detokenize_with_spans(
    tokens: Iterable[str],
) -> tuple[str, tuple[tuple[int, int], ...]]:
    rendered = ""
    spans = []
    previous = ""
    before_previous = ""
    quote_is_open = False
    for token in tokens:
        if not rendered:
            needs_space = False
        elif token == '"':
            needs_space = not quote_is_open and previous not in OPEN_PUNCTUATION
            quote_is_open = not quote_is_open
        elif previous == '"' and quote_is_open:
            needs_space = False
        elif previous == "," and before_previous.isdigit() and token.isdigit():
            needs_space = False
        elif previous == "∼" or (
            previous.isdigit()
            and len(token) > 1
            and token[0] in {"−", "+"}
            and token[1:].isdigit()
        ):
            needs_space = False
        elif token in CLOSE_PUNCTUATION or previous in OPEN_PUNCTUATION:
            needs_space = False
        elif token in JOIN_BOTH_SIDES or previous in JOIN_BOTH_SIDES:
            needs_space = False
        else:
            needs_space = True
        if needs_space:
            rendered += " "
        start = len(rendered)
        rendered += token
        spans.append((start, len(rendered)))
        before_previous = previous
        previous = token
    return rendered, tuple(spans)


def detokenize(tokens: Iterable[str]) -> str:
    return detokenize_with_spans(tokens)[0]


def collapse_entities(rows: list[list[Any]], offset: int, token_count: int) -> tuple[Entity, ...]:
    by_span: dict[tuple[int, int], set[str]] = {}
    for global_start, global_end, label in rows:
        start = global_start - offset
        end = global_end - offset
        if label not in ENTITY_ORDER or not 0 <= start <= end < token_count:
            continue
        by_span.setdefault((start, end), set()).add(label)
    result = []
    for (start, end), labels in by_span.items():
        label = min(labels, key=ENTITY_ORDER.__getitem__)
        result.append(Entity(start, end, label))
    return tuple(sorted(result, key=lambda entity: (entity.start, entity.end, ENTITY_ORDER[entity.type])))


def local_relations(rows: list[list[Any]], offset: int, token_count: int) -> tuple[Relation, ...]:
    result = []
    for global_ss, global_se, global_os, global_oe, label in rows:
        ss, se = global_ss - offset, global_se - offset
        os_, oe = global_os - offset, global_oe - offset
        if label not in RELATION_ORDER:
            continue
        if not (0 <= ss <= se < token_count and 0 <= os_ <= oe < token_count):
            continue
        result.append(Relation(ss, se, os_, oe, label))
    return tuple(result)


def load_records(path: Path, vocabulary: list[str]) -> list[SentenceRecord]:
    records: list[SentenceRecord] = []
    with path.open(encoding="utf-8") as stream:
        for line in stream:
            document = json.loads(line)
            offset = 0
            for sentence_id, (token_ids, ner_rows, relation_rows) in enumerate(
                zip(document["sentences"], document["ner"], document["relations"])
            ):
                tokens = tuple(vocabulary[token_id] for token_id in token_ids)
                records.append(
                    SentenceRecord(
                        doc_id=document["doc_id"],
                        sentence_id=sentence_id,
                        tokens=tokens,
                        text=detokenize(tokens),
                        entities=collapse_entities(ner_rows, offset, len(tokens)),
                        relations=local_relations(relation_rows, offset, len(tokens)),
                    )
                )
                offset += len(tokens)
    return records


def indexed_tokens(record: SentenceRecord) -> list[list[Any]]:
    return [[index, token] for index, token in enumerate(record.tokens)]


def format_full_article_context(records: list[SentenceRecord]) -> str:
    return "\n\n".join(
        f"[Sentence {record.sentence_id}] {record.text}"
        for record in sorted(records, key=lambda record: record.sentence_id)
    )


def entity_dict(entity: Entity, record: SentenceRecord) -> dict[str, Any]:
    return {
        "start": entity.start,
        "end": entity.end,
        "type": entity.type,
        "text": " ".join(record.tokens[entity.start : entity.end + 1]),
    }


def inline_annotated_sentence(record: SentenceRecord) -> str:
    text, token_spans = detokenize_with_spans(record.tokens)
    if "[[" in text or "]]" in text:
        raise RuntimeError(f"sentence {record.key} contains an inline marker delimiter")

    events: dict[int, list[tuple[tuple[int, int, int], str]]] = {}
    for index, entity in enumerate(record.entities, start=1):
        start = token_spans[entity.start][0]
        end = token_spans[entity.end][1]
        events.setdefault(start, []).append(
            ((1, -end, index), f"[[e{index}:{entity.type}]]")
        )
        events.setdefault(end, []).append(
            ((0, -start, index), f"[[/e{index}]]")
        )

    rendered = []
    for offset in range(len(text) + 1):
        rendered.extend(marker for _, marker in sorted(events.get(offset, [])))
        if offset < len(text):
            rendered.append(text[offset])
    return "".join(rendered)


def relation_label_map(record: SentenceRecord) -> dict[tuple[int, int, int, int], str]:
    labels: dict[tuple[int, int, int, int], set[str]] = {}
    for relation in record.relations:
        key = (
            relation.subject_start,
            relation.subject_end,
            relation.object_start,
            relation.object_end,
        )
        labels.setdefault(key, set()).add(relation.label)
        if relation.label in SYMMETRIC_RELATIONS:
            reverse = (key[2], key[3], key[0], key[1])
            labels.setdefault(reverse, set()).add(relation.label)
    return {
        key: min(values, key=RELATION_ORDER.__getitem__)
        for key, values in labels.items()
    }


def build_pair_examples(records: list[SentenceRecord]) -> tuple[list[PairExample], dict[tuple[str, str], list[int]]]:
    examples: list[PairExample] = []
    by_signature: dict[tuple[str, str], list[int]] = {}
    for record_index, record in enumerate(records):
        labels = relation_label_map(record)
        for subject_index, subject in enumerate(record.entities):
            for object_index, object_ in enumerate(record.entities):
                if subject_index == object_index:
                    continue
                key = (subject.start, subject.end, object_.start, object_.end)
                example = PairExample(
                    record_index=record_index,
                    subject=subject,
                    object=object_,
                    label=labels.get(key, "NIL"),
                )
                index = len(examples)
                examples.append(example)
                by_signature.setdefault((subject.type, object_.type), []).append(index)
    return examples, by_signature


def compute_similarities(
    training: list[SentenceRecord],
    targets: list[SentenceRecord],
    model_name: str,
    device: str,
    batch_size: int,
) -> Any:
    try:
        from sentence_transformers import SentenceTransformer
    except ImportError as error:
        raise RuntimeError(
            "sentence-transformers is required; use paper_llm/run_john_qwen.sh"
        ) from error

    model = SentenceTransformer(model_name, device=device)
    training_embeddings = model.encode(
        [record.text for record in training],
        batch_size=batch_size,
        show_progress_bar=True,
        convert_to_numpy=True,
        normalize_embeddings=True,
    )
    target_embeddings = model.encode(
        [record.text for record in targets],
        batch_size=batch_size,
        show_progress_bar=True,
        convert_to_numpy=True,
        normalize_embeddings=True,
    )
    return target_embeddings @ training_embeddings.T


def select_ner_examples(
    records: list[SentenceRecord], scores: Any, k: int, pool_size: int
) -> list[int]:
    ranked = sorted(
        range(len(records)),
        key=lambda index: (-float(scores[index]), records[index].doc_id, records[index].sentence_id),
    )
    remaining = ranked[: max(k, min(pool_size, len(ranked)))]
    selected: list[int] = []
    covered: set[str] = set()
    while remaining and len(selected) < k:
        best = min(
            remaining,
            key=lambda index: (
                -len(records[index].labels - covered),
                -float(scores[index]),
                records[index].doc_id,
                records[index].sentence_id,
            ),
        )
        selected.append(best)
        covered.update(records[best].labels)
        remaining.remove(best)
    return selected


def select_re_examples(
    subject: Entity,
    object_: Entity,
    examples: list[PairExample],
    by_signature: dict[tuple[str, str], list[int]],
    records: list[SentenceRecord],
    scores: Any,
    k: int,
    pool_size: int,
) -> list[PairExample]:
    if not examples:
        raise RuntimeError("training data contains no ordered entity pair for an RE example")

    def rank_key(index: int) -> tuple[Any, ...]:
        example = examples[index]
        record = records[example.record_index]
        return (
            -float(scores[example.record_index]),
            record.doc_id,
            record.sentence_id,
            example.subject.start,
            example.subject.end,
            example.object.start,
            example.object.end,
            example.label,
        )

    preferred = sorted(by_signature.get((subject.type, object_.type), []), key=rank_key)
    ranked = preferred
    if len(ranked) < k:
        preferred_set = set(preferred)
        ranked.extend(
            index
            for index in sorted(range(len(examples)), key=rank_key)
            if index not in preferred_set
        )
    remaining = ranked[: max(k, min(pool_size, len(ranked)))]
    selected: list[int] = []
    covered: set[str] = set()
    while remaining and len(selected) < k:
        best = min(
            remaining,
            key=lambda index: (
                -(examples[index].label not in covered),
                *rank_key(index),
            ),
        )
        selected.append(best)
        covered.add(examples[best].label)
        remaining.remove(best)
    if len(selected) != k:
        raise RuntimeError(f"could select only {len(selected)} of {k} RE examples")
    return [examples[index] for index in selected]


def entity_definitions_text() -> str:
    return "\n".join(f"- `{label}`: {definition}." for label, definition in ENTITY_DEFINITIONS)


def relation_definitions_text() -> str:
    definitions = ["- `NIL`: no listed relation holds for this ordered pair."]
    definitions.extend(
        f"- `{label}`: {definition}." for label, definition in RELATION_DEFINITIONS
    )
    return "\n".join(definitions)


def optional_prompt_sections(full_article: str, examples: str) -> str:
    sections = []
    if full_article:
        sections.append(f"# Full Article Context\n\n{full_article}")
    if examples:
        sections.append(f"# Few-Shot Examples\n\n{examples}")
    if not sections:
        return ""
    return "\n" + "\n\n".join(sections) + "\n"


def render_template(template: str, replacements: dict[str, str]) -> str:
    rendered = template
    for placeholder, value in replacements.items():
        token = "{{" + placeholder + "}}"
        if rendered.count(token) != 1:
            raise RuntimeError(f"expected one {token} in prompt template")
        rendered = rendered.replace(token, value)
    if re.search(r"\{\{[A-Z_]+\}\}", rendered):
        raise RuntimeError("unfilled prompt-template placeholder")
    return rendered


def build_ner_prompt(
    target: SentenceRecord,
    examples: list[SentenceRecord],
    template: str,
    full_article_context: str = "",
    output_format: str = "indices",
) -> str:
    blocks = []
    for number, example in enumerate(examples, start=1):
        if output_format == "indices":
            output = {
                "entities": [
                    {"start": entity.start, "end": entity.end, "type": entity.type}
                    for entity in example.entities
                ]
            }
            blocks.append(
                f"## Example {number}\n\n"
                f"Input: {json.dumps(indexed_tokens(example), ensure_ascii=False)}\n\n"
                f"Output: {json.dumps(output, ensure_ascii=False)}"
            )
        elif output_format == "inline":
            blocks.append(
                f"## Example {number}\n\n"
                f"Input: {example.text}\n\n"
                f"Output: {inline_annotated_sentence(example)}"
            )
        else:
            raise ValueError(f"unknown NER output format: {output_format}")
    examples_text = "\n\n".join(blocks)
    main_input = (
        json.dumps(indexed_tokens(target), ensure_ascii=False)
        if output_format == "indices"
        else target.text
    )
    return render_template(
        template,
        {
            "LABEL_DEFINITIONS": entity_definitions_text(),
            "OPTIONAL_SECTIONS": optional_prompt_sections(
                full_article_context, examples_text
            ),
            "MAIN_INPUT": main_input,
        },
    )


def pair_input(record: SentenceRecord, subject: Entity, object_: Entity) -> dict[str, Any]:
    return {
        "sentence_tokens": indexed_tokens(record),
        "subject": entity_dict(subject, record),
        "object": entity_dict(object_, record),
    }


def build_re_prompt(
    target: SentenceRecord,
    subject: Entity,
    object_: Entity,
    examples: list[tuple[SentenceRecord, PairExample]],
    template: str,
    full_article_context: str = "",
) -> str:
    blocks = []
    for number, (example_record, example) in enumerate(examples, start=1):
        blocks.append(
            f"## Example {number}\n\n"
            f"Input: {json.dumps(pair_input(example_record, example.subject, example.object), ensure_ascii=False)}\n\n"
            f"Output: {json.dumps({'label': example.label})}"
        )
    examples_text = "\n\n".join(blocks)
    return render_template(
        template,
        {
            "LABEL_DEFINITIONS": relation_definitions_text(),
            "OPTIONAL_SECTIONS": optional_prompt_sections(
                full_article_context, examples_text
            ),
            "MAIN_INPUT": json.dumps(pair_input(target, subject, object_), ensure_ascii=False),
        },
    )


def api_json(
    base_url: str,
    path: str,
    payload: dict[str, Any] | None = None,
    timeout: int = 30,
) -> dict[str, Any]:
    data = None
    headers = {"Accept": "application/json"}
    method = "GET"
    if payload is not None:
        data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        headers["Content-Type"] = "application/json"
        method = "POST"
    request = urllib.request.Request(
        f"{base_url.rstrip('/')}{path}", data=data, headers=headers, method=method
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return json.load(response)
    except urllib.error.HTTPError as error:
        detail = error.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"Ollama HTTP {error.code} for {path}: {detail}") from error
    except urllib.error.URLError as error:
        raise RuntimeError(f"cannot reach Ollama at {base_url}: {error.reason}") from error


def response_metrics(response: dict[str, Any]) -> dict[str, Any]:
    result = {
        key: response.get(key)
        for key in (
            "created_at",
            "done",
            "done_reason",
            "total_duration",
            "load_duration",
            "prompt_eval_count",
            "prompt_eval_duration",
            "eval_count",
            "eval_duration",
        )
        if response.get(key) is not None
    }
    count = response.get("eval_count")
    duration = response.get("eval_duration")
    if isinstance(count, int) and isinstance(duration, int) and duration > 0:
        result["generation_tokens_per_second"] = round(
            count / (duration / 1_000_000_000), 3
        )
    return result


def parse_json_content(response: dict[str, Any]) -> tuple[str, Any, str | None]:
    message = response.get("message")
    if not isinstance(message, dict) or not isinstance(message.get("content"), str):
        return "", None, "response has no string message.content"
    content = message["content"].strip()
    try:
        return content, json.loads(content), None
    except json.JSONDecodeError as error:
        return content, None, str(error)


def parse_inline_ner(content: str, tokens: tuple[str, ...]) -> tuple[list[Entity], list[str]]:
    expected_text, token_spans = detokenize_with_spans(tokens)
    plain_parts = []
    plain_offset = 0
    source_offset = 0
    active: dict[str, tuple[int, str]] = {}
    used_ids: set[str] = set()
    completed: list[tuple[int, int, str, str]] = []
    warnings: list[str] = []

    for marker in INLINE_MARKER_RE.finditer(content):
        chunk = content[source_offset : marker.start()]
        plain_parts.append(chunk)
        plain_offset += sum(not character.isspace() for character in chunk)
        source_offset = marker.end()

        close_id = marker.group("close_id")
        if close_id is not None:
            opened = active.pop(close_id, None)
            if opened is None:
                warnings.append(f"closing marker for unopened {close_id}; ignored")
                continue
            start, label = opened
            completed.append((start, plain_offset, label, close_id))
            continue

        open_id = marker.group("open_id")
        if open_id in used_ids:
            warnings.append(f"duplicate marker id {open_id}; later opening ignored")
            continue
        used_ids.add(open_id)
        active[open_id] = (plain_offset, marker.group("label"))

    plain_parts.append(content[source_offset:])
    plain_text = "".join(plain_parts)
    compact_plain = "".join(character for character in plain_text if not character.isspace())
    compact_expected = "".join(
        character for character in expected_text if not character.isspace()
    )
    if compact_plain != compact_expected:
        return [], [
            "text outside inline markers differs from the input sentence beyond "
            "whitespace; all entities ignored",
            *warnings,
        ]

    for marker_id in sorted(active):
        warnings.append(f"unclosed marker {marker_id}; ignored")

    compact_offsets = [0]
    for character in expected_text:
        compact_offsets.append(compact_offsets[-1] + int(not character.isspace()))
    starts = {
        compact_offsets[start]: index for index, (start, _) in enumerate(token_spans)
    }
    ends = {
        compact_offsets[end]: index for index, (_, end) in enumerate(token_spans)
    }
    entities = []
    seen: set[tuple[int, int]] = set()
    for char_start, char_end, label, marker_id in sorted(
        completed,
        key=lambda row: (
            row[0],
            row[1],
            ENTITY_ORDER.get(row[2], len(ENTITY_ORDER)),
            row[3],
        ),
    ):
        if label not in ENTITY_ORDER:
            warnings.append(f"marker {marker_id} has unknown type {label!r}; ignored")
            continue
        if char_start not in starts or char_end not in ends:
            warnings.append(f"marker {marker_id} does not align to token boundaries; ignored")
            continue
        start, end = starts[char_start], ends[char_end]
        if start > end:
            warnings.append(f"marker {marker_id} is empty or reversed; ignored")
            continue
        if (start, end) in seen:
            warnings.append(f"duplicate span ({start}, {end}); later prediction ignored")
            continue
        seen.add((start, end))
        entities.append(Entity(start, end, label))
    return entities, warnings


def sanitize_ner(payload: Any, token_count: int) -> tuple[list[Entity], list[str]]:
    warnings: list[str] = []
    rows = payload.get("entities") if isinstance(payload, dict) else None
    if not isinstance(rows, list):
        return [], ["NER response has no entities array; treated as empty"]
    entities: list[Entity] = []
    seen: set[tuple[int, int]] = set()
    for index, row in enumerate(rows):
        if not isinstance(row, dict):
            warnings.append(f"entities[{index}] is not an object; ignored")
            continue
        start, end, label = row.get("start"), row.get("end"), row.get("type")
        if isinstance(start, bool) or isinstance(end, bool):
            warnings.append(f"entities[{index}] uses boolean coordinates; ignored")
            continue
        if not isinstance(start, int) or not isinstance(end, int):
            warnings.append(f"entities[{index}] has non-integer coordinates; ignored")
            continue
        if label not in ENTITY_ORDER:
            warnings.append(f"entities[{index}] has unknown type {label!r}; ignored")
            continue
        if not 0 <= start <= end < token_count:
            warnings.append(f"entities[{index}] span ({start}, {end}) is out of range; ignored")
            continue
        if (start, end) in seen:
            warnings.append(f"duplicate span ({start}, {end}); later prediction ignored")
            continue
        seen.add((start, end))
        entities.append(Entity(start, end, label))
    entities.sort(key=lambda entity: (entity.start, entity.end, ENTITY_ORDER[entity.type]))
    return entities, warnings


def sanitize_re(payload: Any) -> tuple[str, list[str]]:
    label = payload.get("label") if isinstance(payload, dict) else None
    if label == "NIL" or label in RELATION_ORDER:
        return label, []
    return "NIL", [f"unknown or missing relation label {label!r}; treated as NIL"]


def load_trace(path: Path) -> dict[str, dict[str, Any]]:
    events: dict[str, dict[str, Any]] = {}
    if not path.exists():
        return events
    with path.open(encoding="utf-8") as stream:
        for line_number, line in enumerate(stream, start=1):
            if not line.strip():
                continue
            try:
                event = json.loads(line)
            except json.JSONDecodeError as error:
                raise RuntimeError(f"invalid trace JSON on line {line_number}: {error}") from error
            if isinstance(event, dict) and isinstance(event.get("key"), str):
                events[event["key"]] = event
    return events


def append_trace(path: Path, event: dict[str, Any]) -> None:
    with path.open("a", encoding="utf-8") as stream:
        stream.write(json.dumps(event, ensure_ascii=False, sort_keys=True) + "\n")
        stream.flush()
        os.fsync(stream.fileno())


def ollama_call(
    *,
    key: str,
    stage: str,
    prompt: str,
    args: argparse.Namespace,
    trace_path: Path,
    trace: dict[str, dict[str, Any]],
    metadata: dict[str, Any],
    ner_tokens: tuple[str, ...] | None = None,
) -> tuple[Any, bool]:
    prompt_hash = sha256_bytes(prompt.encode("utf-8"))
    previous = trace.get(key)
    if previous is not None:
        if previous.get("prompt_sha256") != prompt_hash:
            raise RuntimeError(f"resume prompt changed for {key}; use a fresh output directory")
        if bool(previous.get("think", False)) != args.think:
            raise RuntimeError(f"resume thinking mode changed for {key}; use a fresh output directory")
        if stage == "ner" and previous.get("ner_output_format", "indices") != args.ner_output_format:
            raise RuntimeError(f"resume NER output format changed for {key}; use a fresh output directory")
        return previous.get("prediction"), True

    num_predict = args.ner_num_predict if stage == "ner" else args.re_num_predict
    payload = {
        "model": args.model,
        "messages": [{"role": "user", "content": prompt}],
        "stream": False,
        "think": args.think,
        "keep_alive": args.keep_alive,
        "options": {
            "temperature": 0.0,
            "num_ctx": args.num_ctx,
            "num_predict": num_predict,
        },
    }
    if stage == "re" or args.ner_output_format == "indices":
        payload["format"] = "json"
    wall_start = time.monotonic()
    response = api_json(args.base_url, "/api/chat", payload=payload, timeout=args.timeout)
    wall_seconds = time.monotonic() - wall_start
    parse_error = None
    if stage == "ner" and args.ner_output_format == "inline":
        message = response.get("message")
        if not isinstance(message, dict) or not isinstance(message.get("content"), str):
            content = ""
            prediction = []
            warnings = ["response has no string message.content"]
        else:
            content = message["content"].strip()
            if ner_tokens is None:
                raise RuntimeError("inline NER parsing requires the input tokens")
            prediction, warnings = parse_inline_ner(content, ner_tokens)
    else:
        content, parsed, parse_error = parse_json_content(response)
        if stage == "ner":
            prediction, warnings = sanitize_ner(parsed, metadata["token_count"])
        else:
            prediction, warnings = sanitize_re(parsed)

    if stage == "ner":
        serialized_prediction: Any = [
            {"start": entity.start, "end": entity.end, "type": entity.type}
            for entity in prediction
        ]
    else:
        serialized_prediction = prediction
    if parse_error:
        warnings.insert(0, f"invalid JSON: {parse_error}")

    event = {
        "key": key,
        "stage": stage,
        "recorded_at": utc_now(),
        "prompt_sha256": prompt_hash,
        "prompt": prompt,
        "raw_response": content,
        "think": args.think,
        "prediction": serialized_prediction,
        "warnings": warnings,
        "wall_seconds": round(wall_seconds, 6),
        "ollama_metrics": response_metrics(response),
        **metadata,
    }
    message = response.get("message")
    if isinstance(message, dict) and isinstance(message.get("thinking"), str):
        event["raw_thinking"] = message["thinking"]
    if stage == "ner":
        event["ner_output_format"] = args.ner_output_format
    append_trace(trace_path, event)
    trace[key] = event
    return serialized_prediction, False


def git_commit(repo_root: Path) -> str | None:
    completed = subprocess.run(
        ["git", "-C", str(repo_root), "rev-parse", "HEAD"],
        check=False,
        capture_output=True,
        text=True,
    )
    return completed.stdout.strip() if completed.returncode == 0 else None


def gpu_inventory() -> list[str]:
    try:
        completed = subprocess.run(
            [
                "nvidia-smi",
                "--query-gpu=name,uuid,memory.total,driver_version",
                "--format=csv,noheader",
            ],
            check=False,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        return []
    if completed.returncode != 0:
        return []
    return [line.strip() for line in completed.stdout.splitlines() if line.strip()]


def package_version(name: str) -> str | None:
    try:
        return importlib.metadata.version(name)
    except importlib.metadata.PackageNotFoundError:
        return None


def model_record(tags: dict[str, Any], requested_model: str) -> dict[str, Any] | None:
    aliases = {requested_model, f"{requested_model}:latest"}
    if ":" not in requested_model:
        aliases.add(f"{requested_model}:latest")
    for model in tags.get("models", []):
        if aliases & {model.get("name"), model.get("model")}:
            return {
                key: model.get(key)
                for key in ("name", "model", "digest", "size", "modified_at", "details")
                if model.get(key) is not None
            }
    return None


def parse_args() -> argparse.Namespace:
    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default="qwen3.8:27b")
    parser.add_argument("--base-url", default="http://127.0.0.1:11434")
    parser.add_argument("--document-id", default=DEFAULT_DOCUMENT_ID)
    parser.add_argument("--target-data", type=Path, default=repo_root / "data" / "train.jsonl")
    parser.add_argument("--training-data", type=Path, default=repo_root / "data" / "train.jsonl")
    parser.add_argument("--vocabulary", type=Path, default=repo_root / "vocabulary.json")
    parser.add_argument(
        "--ner-output-format",
        choices=NER_OUTPUT_FORMATS,
        default="indices",
        help="have NER predict token indices or mark entities in a copied sentence",
    )
    parser.add_argument("--ner-template", type=Path)
    parser.add_argument("--re-template", type=Path, default=script_dir / "re_prompt.md")
    parser.add_argument("--retriever", default=DEFAULT_RETRIEVER)
    parser.add_argument("--retriever-device", default="cpu")
    parser.add_argument("--embedding-batch-size", type=int, default=64)
    parser.add_argument("--ner-shots", type=int, default=10)
    parser.add_argument("--re-shots", type=int, default=1)
    parser.add_argument("--retrieval-pool-size", type=int, default=100)
    parser.add_argument("--num-ctx", type=int, default=32768)
    parser.add_argument("--ner-num-predict", type=int, default=2048)
    parser.add_argument("--re-num-predict", type=int, default=64)
    parser.add_argument("--keep-alive", default="30m")
    parser.add_argument("--timeout", type=int, default=3600)
    parser.add_argument("--think", action="store_true")
    parser.add_argument(
        "--full-article-context",
        action="store_true",
        help="include the full target article before the few-shot examples",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=script_dir / "results" / "qwen3.8-27b-ollama-john-00016_2106_09462",
    )
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()
    if (args.ner_shots, args.re_shots) not in {(10, 1), (10, 5), (10, 10), (0, 0)}:
        parser.error(
            "supported ICL configurations are --ner-shots 10 with --re-shots 1, 5, or 10, "
            "or both zero"
        )
    if args.resume and args.overwrite:
        parser.error("--resume and --overwrite are mutually exclusive")
    if args.ner_template is None:
        template_name = (
            "ner_prompt.md"
            if args.ner_output_format == "indices"
            else "ner_prompt_inline.md"
        )
        args.ner_template = script_dir / template_name
    return args


def main() -> None:
    args = parse_args()
    zero_icl = args.ner_shots == 0 and args.re_shots == 0
    started_at = utc_now()
    wall_start = time.monotonic()
    output_dir = args.output_dir.resolve()
    trace_path = output_dir / "trace.jsonl"
    prediction_path = output_dir / "prediction.json"
    retrieval_path = output_dir / "retrieval.json"
    run_path = output_dir / "run.json"
    known_outputs = (trace_path, prediction_path, retrieval_path, run_path)
    if args.overwrite:
        for path in known_outputs:
            path.unlink(missing_ok=True)
    elif any(path.exists() for path in known_outputs) and not args.resume:
        raise SystemExit(f"result files already exist in {output_dir}; use --resume or --overwrite")
    output_dir.mkdir(parents=True, exist_ok=True)

    vocabulary = json.loads(args.vocabulary.read_text(encoding="utf-8"))
    target_records_all = load_records(args.target_data, vocabulary)
    targets = [record for record in target_records_all if record.doc_id == args.document_id]
    if not targets:
        raise RuntimeError(f"document {args.document_id!r} not found in {args.target_data}")
    training: list[SentenceRecord] = []
    similarities: Any = None
    pair_examples: list[PairExample] = []
    pairs_by_signature: dict[tuple[str, str], list[int]] = {}
    if zero_icl:
        print("Running with zero ICL examples; retrieval is disabled", flush=True)
    else:
        training_all = load_records(args.training_data, vocabulary)
        training = [record for record in training_all if record.doc_id != args.document_id]
        if len(training) < args.ner_shots:
            raise RuntimeError("not enough leakage-free training sentences for NER examples")
        print(
            f"Embedding {len(training)} training sentences and {len(targets)} target sentences "
            f"with {args.retriever}",
            flush=True,
        )
        similarities = compute_similarities(
            training,
            targets,
            args.retriever,
            args.retriever_device,
            args.embedding_batch_size,
        )
        pair_examples, pairs_by_signature = build_pair_examples(training)
        if not pair_examples:
            raise RuntimeError("training data has no RE demonstration candidates")

    ner_template = args.ner_template.read_text(encoding="utf-8")
    re_template = args.re_template.read_text(encoding="utf-8")
    full_article_context = (
        format_full_article_context(targets) if args.full_article_context else ""
    )
    trace = load_trace(trace_path) if args.resume else {}
    predictions_by_sentence: list[list[Entity]] = []
    ner_retrieval: list[dict[str, Any]] = []
    resumed_calls = 0
    new_calls = 0

    for target_index, target in enumerate(targets):
        selected_indices = []
        if not zero_icl:
            selected_indices = select_ner_examples(
                training,
                similarities[target_index],
                args.ner_shots,
                args.retrieval_pool_size,
            )
        examples = [training[index] for index in selected_indices]
        prompt = build_ner_prompt(
            target,
            examples,
            ner_template,
            full_article_context=full_article_context,
            output_format=args.ner_output_format,
        )
        key = f"ner:{target.sentence_id}"
        print(f"[NER {target_index + 1}/{len(targets)}] sentence {target.sentence_id}", flush=True)
        serialized, resumed = ollama_call(
            key=key,
            stage="ner",
            prompt=prompt,
            args=args,
            trace_path=trace_path,
            trace=trace,
            metadata={
                "document_id": target.doc_id,
                "sentence_id": target.sentence_id,
                "token_count": len(target.tokens),
                "example_keys": [example.key for example in examples],
            },
            ner_tokens=target.tokens,
        )
        resumed_calls += int(resumed)
        new_calls += int(not resumed)
        predicted = [Entity(row["start"], row["end"], row["type"]) for row in serialized]
        predictions_by_sentence.append(predicted)
        ner_retrieval.append(
            {
                "sentence_id": target.sentence_id,
                "examples": [
                    {
                        "document_id": training[index].doc_id,
                        "sentence_id": training[index].sentence_id,
                        "cosine_similarity": round(float(similarities[target_index][index]), 9),
                        "entity_labels": sorted(training[index].labels, key=ENTITY_ORDER.__getitem__),
                    }
                    for index in selected_indices
                ],
            }
        )

    total_pairs = sum(len(entities) * (len(entities) - 1) for entities in predictions_by_sentence)
    pair_number = 0
    predicted_relation_rows: list[tuple[int, int, int, str]] = []
    re_retrieval: list[dict[str, Any]] = []
    for target_index, (target, entities) in enumerate(zip(targets, predictions_by_sentence)):
        for subject_index, subject in enumerate(entities):
            for object_index, object_ in enumerate(entities):
                if subject_index == object_index:
                    continue
                pair_number += 1
                examples: list[PairExample] = []
                if not zero_icl:
                    examples = select_re_examples(
                        subject,
                        object_,
                        pair_examples,
                        pairs_by_signature,
                        training,
                        similarities[target_index],
                        args.re_shots,
                        args.retrieval_pool_size,
                    )
                prompt_examples = [
                    (training[example.record_index], example) for example in examples
                ]
                prompt = build_re_prompt(
                    target,
                    subject,
                    object_,
                    prompt_examples,
                    re_template,
                    full_article_context=full_article_context,
                )
                key = f"re:{target.sentence_id}:{subject_index}:{object_index}"
                print(
                    f"[RE {pair_number}/{total_pairs}] sentence {target.sentence_id} "
                    f"pair {subject_index}->{object_index}",
                    flush=True,
                )
                label, resumed = ollama_call(
                    key=key,
                    stage="re",
                    prompt=prompt,
                    args=args,
                    trace_path=trace_path,
                    trace=trace,
                    metadata={
                        "document_id": target.doc_id,
                        "sentence_id": target.sentence_id,
                        "token_count": len(target.tokens),
                        "subject_index": subject_index,
                        "object_index": object_index,
                        "example_key": prompt_examples[0][0].key if prompt_examples else None,
                        "example_keys": [record.key for record, _ in prompt_examples],
                    },
                )
                resumed_calls += int(resumed)
                new_calls += int(not resumed)
                if label != "NIL":
                    predicted_relation_rows.append(
                        (target_index, subject_index, object_index, label)
                    )
                re_retrieval.append(
                    {
                        "sentence_id": target.sentence_id,
                        "subject_index": subject_index,
                        "object_index": object_index,
                        "example": None
                        if not prompt_examples
                        else {
                            "document_id": prompt_examples[0][0].doc_id,
                            "sentence_id": prompt_examples[0][0].sentence_id,
                            "subject": entity_dict(
                                prompt_examples[0][1].subject, prompt_examples[0][0]
                            ),
                            "object": entity_dict(
                                prompt_examples[0][1].object, prompt_examples[0][0]
                            ),
                            "label": prompt_examples[0][1].label,
                            "cosine_similarity": round(
                                float(
                                    similarities[target_index][
                                        prompt_examples[0][1].record_index
                                    ]
                                ),
                                9,
                            ),
                        },
                        "examples": [
                            {
                                "document_id": record.doc_id,
                                "sentence_id": record.sentence_id,
                                "subject": entity_dict(example.subject, record),
                                "object": entity_dict(example.object, record),
                                "label": example.label,
                                "cosine_similarity": round(
                                    float(similarities[target_index][example.record_index]), 9
                                ),
                            }
                            for record, example in prompt_examples
                        ],
                    }
                )

    output_entities: list[dict[str, Any]] = []
    ids_by_position: dict[tuple[int, int], str] = {}
    for target_index, (target, entities) in enumerate(zip(targets, predictions_by_sentence)):
        for entity_index, entity in enumerate(entities):
            entity_id = f"s{target.sentence_id}e{entity_index}"
            ids_by_position[(target_index, entity_index)] = entity_id
            output_entities.append(
                {
                    "id": entity_id,
                    "segment_id": target.sentence_id,
                    "start": entity.start,
                    "end": entity.end,
                    "type": entity.type,
                    "text": " ".join(target.tokens[entity.start : entity.end + 1]),
                }
            )

    relation_set: set[tuple[str, str, str]] = set()
    for target_index, subject_index, object_index, label in predicted_relation_rows:
        head = ids_by_position[(target_index, subject_index)]
        tail = ids_by_position[(target_index, object_index)]
        if label in SYMMETRIC_RELATIONS and tail < head:
            head, tail = tail, head
        relation_set.add((head, label, tail))
    output_relations = [
        {"head": head, "type": label, "tail": tail}
        for head, label, tail in sorted(relation_set)
    ]
    prediction = {
        "document_id": args.document_id,
        "entities": output_entities,
        "relations": output_relations,
    }
    prediction_path.write_text(
        json.dumps(prediction, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    retrieval = {
        "schema_version": 1,
        "retriever": None if zero_icl else args.retriever,
        "selection": {
            "name": "none (zero ICL)" if zero_icl else "reconstructed similar+diverse",
            "ner_shots": args.ner_shots,
            "ner_pool_size": 0 if zero_icl else args.retrieval_pool_size,
            "ner_reranking": None
            if zero_icl
            else "greedy maximum new entity-label coverage, cosine tie-break",
            "re_shots": args.re_shots,
            "re_reranking": None
            if zero_icl
            else (
                "greedy maximum new relation-label coverage within matching ordered "
                "entity-type signature, cosine tie-break"
                if args.re_shots > 1
                else "highest sentence cosine among matching ordered entity-type signature"
            ),
        },
        "training_source": None if zero_icl else str(args.training_data),
        "excluded_document_id": None if zero_icl else args.document_id,
        "ner": ner_retrieval,
        "re": re_retrieval,
    }
    retrieval_path.write_text(
        json.dumps(retrieval, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    tags = api_json(args.base_url, "/api/tags", timeout=30)
    server_version = api_json(args.base_url, "/api/version", timeout=30)
    warning_count = sum(len(event.get("warnings", [])) for event in trace.values())
    repo_root = Path(__file__).resolve().parents[1]
    run = {
        "schema_version": 1,
        "method": "GSAP-ERE paper LLM pipeline reconstruction",
        "method_separation": "not the full-article zero-shot method in zero_shot/",
        "paper_reported_steps": {
            "unit": "sentence",
            "pipeline": ["NER", "ordered predicted-entity-pair RE"],
            "ner_shots": 10,
            "re_shots": 1,
            "example_selection": "similar+diverse from training split",
            "retriever": DEFAULT_RETRIEVER,
            "inference_framework": "Ollama",
            "temperature": 0.0,
        },
        "actual_icl_configuration": {
            "ner_shots": args.ner_shots,
            "re_shots": args.re_shots,
            "retrieval_enabled": not zero_icl,
            "ner_output_format": args.ner_output_format,
        },
        "unreleased_details_reconstructed": [
            "exact Appendix A.3 NER and RE prompt wording",
            "exact unique-label re-ranking implementation",
            "exact LLM response parsing",
        ],
        "target": {
            "document_id": args.document_id,
            "data_path": str(args.target_data),
            "sentence_count": len(targets),
            "gold_annotations_sent_to_llm": False,
            "excluded_from_demonstrations": True,
        },
        "model": {
            "requested": args.model,
            "ollama_record": model_record(tags, args.model),
            "think": args.think,
        },
        "retrieval": {
            "model": None if zero_icl else args.retriever,
            "device": None if zero_icl else args.retriever_device,
            "training_sentence_count": len(training),
            "training_pair_example_count": len(pair_examples),
            "pool_size": 0 if zero_icl else args.retrieval_pool_size,
        },
        "request": {
            "ner_response_format": args.ner_output_format,
            "re_response_format": "json",
            "think": args.think,
            "full_article_context": args.full_article_context,
            "temperature": 0.0,
            "num_ctx": args.num_ctx,
            "ner_num_predict": args.ner_num_predict,
            "re_num_predict": args.re_num_predict,
            "keep_alive": args.keep_alive,
        },
        "counts": {
            "predicted_entities": len(output_entities),
            "ordered_re_candidates": total_pairs,
            "predicted_non_nil_relations": len(output_relations),
            "new_calls_this_attempt": new_calls,
            "resumed_calls": resumed_calls,
            "response_warning_count": warning_count,
        },
        "artifacts": {
            "prediction": {
                "path": str(prediction_path.relative_to(repo_root)),
                "sha256": sha256_file(prediction_path),
            },
            "trace": {
                "path": str(trace_path.relative_to(repo_root)),
                "sha256": sha256_file(trace_path),
            },
            "retrieval": {
                "path": str(retrieval_path.relative_to(repo_root)),
                "sha256": sha256_file(retrieval_path),
            },
        },
        "inputs": {
            "target_data_sha256": sha256_file(args.target_data),
            "training_data_sha256": None if zero_icl else sha256_file(args.training_data),
            "vocabulary_sha256": sha256_file(args.vocabulary),
            "ner_template_sha256": sha256_file(args.ner_template),
            "re_template_sha256": sha256_file(args.re_template),
            "inference_script_sha256": sha256_file(Path(__file__)),
        },
        "software": {
            "python": platform.python_version(),
            "ollama_server": server_version.get("version"),
            "sentence-transformers": package_version("sentence-transformers"),
            "torch": package_version("torch"),
            "gsapere": package_version("gsapere"),
        },
        "system": {
            "hostname": socket.gethostname(),
            "platform": platform.platform(),
            "gpus": gpu_inventory(),
        },
        "git_commit": git_commit(repo_root),
        "started_at": started_at,
        "finished_at": utc_now(),
        "wall_seconds": round(time.monotonic() - wall_start, 6),
    }
    run_path.write_text(json.dumps(run, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(
        f"Wrote {prediction_path} with {len(output_entities)} entities and "
        f"{len(output_relations)} relations",
        flush=True,
    )


if __name__ == "__main__":
    main()
